# Generated by Django 3.0.5 on 2020-05-03 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 1, 26, 5, 679690, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 1, 26, 5, 678626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 1, 26, 5, 679197, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 1, 26, 5, 681219, tzinfo=utc))),
                ('first_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user_id', to='api.User')),
                ('second_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user_id', to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 1, 26, 5, 680601, tzinfo=utc))),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
